### ISSUE TITLE
How to deal with apparent DS-annotations insensitive projects ?

### ISSUE THREAD

**Issue by ThomasElskens** [ecliptical/ds-annotations#12]
Hello,

I'm using the ds annotations support in an Eclipse RCP 4 application. This works fine for most projects, but there is one project which stubbornly ignores the annotations. 

I've checked quite everything : the dependencies in the manifest, the project & classpath settings... I can't figure out why most projects work well, and this one not. 

I've noticed that in the metadata of my Eclipse workplace, all the plugins using the DS annotation support have a file "state.dat" in .metadata\.plugins\org.eclipse.core.resources\.projects\${project.name}\ca.ecliptical.pde.ds

The faulty plugin does not have this file. 

Any hint would be appreciated,

Thomas Elskens

**Comment by pnehrer** [comment]
Hi Thomas,

it sounds like the project isn't processed by the plugin. The plugin only works on JDT projects that:
1. have DS Annotations enabled in Project Properties (`Generate descriptors from annotated sources`; defaults to true)
2. are PDE projects
3. have type org.osgi.service.component.annotations.Component resolved on their classpath

If all that is true and you're still not getting the expected results, is there any way you could share the project in question, or a similar one that exhibits this behavior?

If not, can you enable debug tracing for the DS Annotations plugin and share the output:

1. create a file (e.g., /tmp/debug.options) with the following content:
> ca.ecliptical.pde.ds/debug=true
> ca.ecliptical.pde.ds/ds-annotation-builder=true
> ca.ecliptical.pde.ds/ds-annotation-builder/processor=true

2. start your Eclipse with `-debug /tmp/debug.options` command-line argument; the trace output will be in your `${workspace}/.metadata/trace.log` (you can change that through `Preferences -> General -> Tracing`)

Thanks!

**Comment by ThomasElskens** [comment]
Hi Peter,

I wouldn't mind sharing the offending plugin, but this seems very non-trivial to achieve on the github issue tracker. With this url, you can already find the output of trace.log : https://gist.github.com/ThomasElskens/77a7ea914c5540f8f6d4#file-debug-options

Several projects miss the state.dat file, but the only one where this is not normal is be.groups.portfolio.service.adapterproviders (the other ones do not contain DS). 

The three conditions are met:
1. All projects use general settings for DS Annotations,
2. All projects have the org.eclipse.pde.PluginNature and org.eclipse.jdt.core.javanature in their .project file. 
3. As I'm using Equinox, I always have to require the bundle org.eclipse.osgi.services for DS to work. This plugin exports the package org.osgi.service.component.annotations. 

Anyhow, I fixed the problem like this : I removed the faulty plugin, created a new one, and copied the java files into it. Now the DS annotations support works perfectly. 

Thomas

**Comment by pnehrer** [comment]
Thank you Thomas. The trace log doesn't show anything unusual -- the project in question is indeed processed but no annotated classes are found in it (for an unknown reason). I'll add additional debug statements around that code but nothing obvious jumps out at the moment.

In any case I'm glad you were able to work around the issue. Please reopen this issue if the problem reoccurs. Thank you for your submission.
