### ISSUE TITLE
Eclipse Line Delimiters Setting is ignored

### ISSUE THREAD

**Issue by mgcenit** [ecliptical/ds-annotations#18]
The Eclipse Line Delimiters Setting under "General/Workspace New text file line delimiter" to "Other: Unix" is ignored on Windows.

New Component files created are using Line Delimiters based on the OS instead.
Also, changing the Delimiters in Eclipse via "File / Convert Line Delimiters To / Unix" only lasts until changes to the classes are made and DS-Annotations rewrites the files with the wrong delmiters again.

**Comment by pnehrer** [comment]
Fixed in v1.2.7.
