### ISSUE TITLE
Should provide QuickFix if annotations are not on classpath

### ISSUE THREAD

**Issue by guw** [ecliptical/ds-annotations#19]
Would be cool if there is a QuickFix that puts the annotations library into build.properties. Wondering if there should also be a warning for all PDE projects without annotations on the classpath?

**Comment by pnehrer** [comment]
Good idea for use-cases involving annotations but users who don't use annotations might find it annoying  to get a warning on such projects. I'll see how this can be combined with issue #20.

Perhaps it would make sense to:
1. always make annotations available to PDE/JDT projects (via plugin classpath container contribution as in issue #20)
2. put up a warning when they're actually referenced in the project -- the user would then have to place them on the "permanent" classpath (via a quick fix) or make sure the contributor is available to their automated build system (e.g., outside of the IDE)... I have to think more about this.

**Comment by pnehrer** [comment]
Here's what I was able to do:

1. contribute annotations to every plugin project via plugin classpath container contribution, which isn't available to external builders (e.g., PDE export, etc.- *unless* the new plugin ca.ecliptical.pde.ds.classpath is part of the builder, which is not a viable option in most cases)
2. when finishing a build of a project that contains annotated classes and not finding another annotations provider on the classpath, create a problem marker
3. three marker resolutions to add annotations to project's permanent build path, after which the marker is removed

As a result, projects that already have annotations on their "permanent" build path (through any means) will never see the marker; only new projects that are not yet set up with annotations on their permanent build path will ever see it.
