### ISSUE TITLE
Problem running a configuration with generated ds-annotations

### ISSUE THREAD

**Issue by jcr2015** [ecliptical/ds-annotations#22]
Hi Peter
Thank for this plugin.
I use it with the option A on a simple project.
Generation of *.xml works well but at runtime I have a set of ennoying
bundles which are added and unfortunately trigger several errors.
I don't know if it s a bug or a wrong configuration on my side.
Of course I can give more detail, even the source code which is really small.
Thank for your help

Eclipse SDK Version: Mars.1 (4.5.1) Build id: M20150904-0015

Enclosed is a part of the message trace, I can send the full list if necessary.

!SESSION 2016-01-12 10:18:00.124 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_65
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=fr_FR
Command-line arguments:  -dev file:.../MONASTIR/.metadata/.plugins/org.eclipse.pde.core/ClientServerDSWithA/dev.properties -os macosx -ws cocoa -arch x86_64 -consoleLog -console

!ENTRY org.eclipse.update.configurator 4 0 2016-01-12 10:18:01.362
!MESSAGE Could not install bundle plugins/ca.ecliptical.pde.ds.classpath_1.0.0.v20151122-2215.jar   A bundle is already installed with the name "ca.ecliptical.pde.ds.classpath" and version "1.0.0.v20151122-2215"

!ENTRY org.eclipse.update.configurator 4 0 2016-01-12 10:18:01.363
!MESSAGE Could not install bundle plugins/ca.ecliptical.pde.ds_1.2.8.v20151122-2215.jar   A bundle is already installed with the name "ca.ecliptical.pde.ds" and version "1.2.8.v20151122-2215"

!ENTRY org.eclipse.update.configurator 4 0 2016-01-12 10:18:01.365
!MESSAGE Could not install bundle plugins/com.ibm.icu_54.1.1.v201501272100.jar   A bundle is already installed with the name "com.ibm.icu" and version "54.1.1.v201501272100"

!ENTRY org.eclipse.update.configurator 4 0 2016-01-12 10:18:01.366
!MESSAGE Could not install bundle plugins/javax.annotation_1.2.0.v201401042248.jar   A bundle is already installed with the name "javax.annotation" and version "1.2.0.v201401042248"

!ENTRY org.eclipse.update.configurator 4 0 2016-01-12 10:18:01.367
!MESSAGE Could not install bundle plugins/javax.inject_1.0.0.v20091030.jar   A bundle is already installed with the name "javax.inject" and version "1.0.0.v20091030"

**Comment by pnehrer** [comment]
Thank you for you report. I believe this is a general issue (not DS specific) related to your launch configuration. Can you clean it (e.g., in launch config dialog, click Settings and check Clear configuration area before launching) or create a completely new launch configuration?

I cannot reproduce it on my end but have seen similar reports for other Eclipse-related projects when I googled the error message.

**Comment by jcr2015** [comment]
OK thank
Your are right this is a configuration problem, setting clear before launching solves the problem.
